// demo-solid/src/components/Layout.tsx
import { AppScreen } from "@contentstech/stackflow-plugin-basic-ui/solid";
import type { Component, JSXElement } from "solid-js";

type PropOf<T> = T extends Component<infer U> ? U : never;

interface LayoutProps {
  appBar?: PropOf<typeof AppScreen>["appBar"];
  children: JSXElement;
}
const Layout: Component<LayoutProps> = ({ appBar, children }) => (
  <AppScreen appBar={appBar}>{children}</AppScreen>
);

export default Layout;

// demo/src/components/Layout.tsx
import { AppScreen } from "@contentstech/stackflow-plugin-basic-ui";

type PropOf<T> = T extends React.ComponentType<infer U> ? U : never;

interface LayoutProps {
  appBar?: PropOf<typeof AppScreen>["appBar"];
  children: React.ReactNode;
}
const Layout: React.FC<LayoutProps> = ({ appBar, children }) => (
  <AppScreen appBar={appBar}>{children}</AppScreen>
);

Layout.displayName = "Layout";

export default Layout;
