// integrations/solid/src/MainRenderer.tsx
import type { Component } from "solid-js";
import { mergeProps } from "solid-js";

import PluginRenderer, { createPluginRenderProps } from "./PluginRenderer";
import type { ActivityComponentType } from "./activity";
import { useCoreState } from "./core";
import { usePlugins } from "./plugins";
import type { WithRequired } from "./utils";

interface MainRendererProps {
  activityComponentMap: {
    [key: string]: ActivityComponentType;
  };
  initialContext: any;
}
const MainRenderer: Component<MainRendererProps> = (props) => {
  const { stack } = useCoreState();
  const plugins = usePlugins();

  const renderingPlugins = plugins.filter(
    (plugin): plugin is WithRequired<typeof plugin, "render"> =>
      !!plugin.render,
  );

  if (renderingPlugins.length === 0) {
    console.warn(
      "Stackflow -" +
        ` There is no rendering plugin, so "<Stack />" doesn't render anything.` +
        ` If you want to render some UI, use "@contentstech/stackflow-plugin-renderer-basic"` +
        " or add another rendering plugin.",
    );
  }

  const pluginRenderProps = createPluginRenderProps({
    activityComponentMap: props.activityComponentMap,
    initialContext: () => props.initialContext,
  });

  const render = plugins.reduce(
    (render, p) => {
      if (!p.wrapStack) {
        return render;
      }

      return () =>
        p.wrapStack?.({
          stack: mergeProps(stack, { render }),
          initialContext: () => props.initialContext,
        });
    },
    () => (
      <>
        {renderingPlugins.map((plugin) => (
          <PluginRenderer plugin={plugin} renderProps={pluginRenderProps} />
        ))}
      </>
    ),
  );

  return render();
};

export default MainRenderer;

// integrations/react/src/MainRenderer.tsx
import { useEffect } from "react";

import PluginRenderer from "./PluginRenderer";
import type { ActivityComponentType } from "./activity";
import { useCoreState } from "./core";
import { usePlugins } from "./plugins";
import type { WithRequired } from "./utils";

interface MainRendererProps {
  activityComponentMap: {
    [key: string]: ActivityComponentType;
  };
  initialContext: any;
}
const MainRenderer: React.FC<MainRendererProps> = ({
  activityComponentMap,
  initialContext,
}) => {
  const coreState = useCoreState();
  const plugins = usePlugins();

  const renderingPlugins = plugins.filter(
    (plugin): plugin is WithRequired<typeof plugin, "render"> =>
      !!plugin.render,
  );

  useEffect(() => {
    if (renderingPlugins.length === 0) {
      console.warn(
        "Stackflow -" +
          ` There is no rendering plugin, so "<Stack />" doesn't render anything.` +
          ` If you want to render some UI, use "@contentstech/stackflow-plugin-renderer-basic"` +
          " or add another rendering plugin.",
      );
    }
  }, [renderingPlugins]);

  let output = (
    <>
      {renderingPlugins.map((plugin) => (
        <PluginRenderer
          key={plugin.key}
          activityComponentMap={activityComponentMap}
          plugin={plugin}
          initialContext={initialContext}
        />
      ))}
    </>
  );

  plugins.forEach((plugin) => {
    output =
      plugin.wrapStack?.({
        stack: {
          ...coreState,
          render() {
            return output;
          },
        },
        initialContext,
      }) ?? output;
  });

  return output;
};

MainRenderer.displayName = "MainRenderer";

export default MainRenderer;
